version: '3'
services:
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    volumes:
      - /home/user/.data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 1000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  db:
    image: mariadb
    container_name: idx-db-1
    command: ["mariadbd", "--pid-file=/tmp/mysqld.pid"]
    environment:
       MARIADB_ROOT_PASSWORD: root
       MARIADB_DATABASE: moodle
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8020:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
# At the end of your docker-compose file
volumes:
  mariadb_data: